.

diff --git a/LWplot_BR b/LWplot_BR
--- a/LWplot_BR
+++ b/LWplot_BR
@@ -2,13 +2,14 @@
 #======================================================================
 #					 L W P L O T _ B R 
 #                    doc: Mon Oct 17 10:57:12 2011
-#                    dlm: Tue Oct 18 16:24:12 2011
+#                    dlm: Mon Nov 14 15:02:29 2011
 #                    (c) 2011 A.M. Thurnherr
-#                    uE-Info: 62 97 NIL 0 0 72 2 2 4 NIL ofnI
+#                    uE-Info: 39 79 NIL 0 0 72 2 2 4 NIL ofnI
 #======================================================================
 
 # HISTORY:
 #	Oct 17, 2011: - created
+#	Nov 14, 2011: - added file layout check
 
 #--------------------------------------------------
 # Usage
@@ -17,6 +18,7 @@
 USAGE="Usage: $0 <eps-file> [in-file]"
 	[ $# -eq 2 ] && exec <"$2" "$0" "$1"
 	[ $# -ne 1 ] && { echo $USAGE >&2; exit 1; }
+eps_file="$1"
 
 #--------------------------------------------------
 # Read Header Data
@@ -32,6 +34,18 @@ do
 	[ -z "$fields" ] && fields=`expr -- "$line" : '#ANTS#FIELDS# \(.*\)' | sed -e s/{//g -e s/}//g`
 done
 
+set -- $fields
+[ "$1" = bin -a \
+  "$2" = dc_residual -a "$3" = dc_residual.sig -a "$4" = dc_residual.nsamp -a \
+  "$5" = uc_residual -a "$6" = uc_residual.sig -a "$7" = uc_residual.nsamp ] || {
+		echo "$0: file layout error" >&2
+		exit 1
+}
+
+#--------------------------------------------------
+# Plot Data
+#--------------------------------------------------
+
 TMPFILE=/tmp/$$.LWplot_BR
 if [ ! -t 1 ]
 then
@@ -39,10 +53,6 @@ then
 else
 	cat > $TMPFILE
 fi
-
-#--------------------------------------------------
-# Plot Data
-#--------------------------------------------------
 
 [ -f .gmtdefaults4 ] ||
 	gmtset	PAPER_MEDIA letter+ \
@@ -54,17 +64,17 @@ R=-R-0.07/0.07/0.5/`echo $max_bin+0.5|bc`
 U=-R0/1/0/1
 X=-JX10/-10
 
-echo -e "0 0.5\n0 `echo $max_bin+0.5|bc`" | psxy -P -K $R $X > "$1"
+echo -e "0 0.5\n0 `echo $max_bin+0.5|bc`" | psxy -P -K $R $X > "$eps_file"
 
-awk '{print $2, $1}' $TMPFILE | psxy -O -K -Mn $R $X -W4/coral >> "$1"
-awk '{print $5, $1}' $TMPFILE | psxy -O -K -Mn $R $X -W4/SeaGreen >> "$1"
-awk '{print $2, $1, ($4>1)?($3/sqrt($4-1)):0}' $TMPFILE | psxy -O -K -Mn $R $X -Ex0.2c/4/coral >> "$1"
-awk '{print $5, $1, ($7>1)?($6/sqrt($7-1)):0}' $TMPFILE | psxy -O -K -Mn $R $X -Ex0.2c/4/SeaGreen >> "$1"
+awk '{print $2, $1}' $TMPFILE | psxy -O -K -Mn $R $X -W4/coral >> "$eps_file"
+awk '{print $5, $1}' $TMPFILE | psxy -O -K -Mn $R $X -W4/SeaGreen >> "$eps_file"
+awk '{print $2, $1, ($4>1)?($3/sqrt($4-1)):0}' $TMPFILE | psxy -O -K -Mn $R $X -Ex0.2c/4/coral >> "$eps_file"
+awk '{print $5, $1, ($7>1)?($6/sqrt($7-1)):0}' $TMPFILE | psxy -O -K -Mn $R $X -Ex0.2c/4/SeaGreen >> "$eps_file"
 	
-echo 0.02 0.02 12 0 0 TL $out_basename $run_label| pstext -O -K $U $X >> "$1"
+echo 0.02 0.02 12 0 0 TL $out_basename $run_label| pstext -O -K $U $X >> "$eps_file"
 
-psbasemap -O -K $R $X -Bf0.005a0.05:"Residual Vertical Velocity [m/s]":/f1a5:"Bin [#]":WeSn >> "$1"
-psbasemap -O $R $X -B/a100-99W >> "$1"
+psbasemap -O -K $R $X -Bf0.005a0.05:"Residual Vertical Velocity [m/s]":/f1a5:"Bin [#]":WeSn >> "$eps_file"
+psbasemap -O $R $X -B/a100-99W >> "$eps_file"
 
 rm $TMPFILE
-fixbb "$1"
+fixbb "$eps_file"
diff --git a/LWplot_Sv b/LWplot_Sv
--- a/LWplot_Sv
+++ b/LWplot_Sv
@@ -2,14 +2,15 @@
 #======================================================================
 #					 L W P L O T _ S V 
 #                    doc: Sat Oct 15 13:42:50 2011
-#                    dlm: Mon Oct 24 10:28:40 2011
+#                    dlm: Mon Nov 14 14:57:31 2011
 #                    (c) 2011 A.M. Thurnherr
-#                    uE-Info: 12 55 NIL 0 0 72 2 2 4 NIL ofnI
+#                    uE-Info: 76 26 NIL 0 0 72 2 2 4 NIL ofnI
 #======================================================================
 
 # HISTORY:
 #	Oct 19, 2011: - adapted from [LWplot_residuals]
 #	Oct 24, 2011: - LADCP_bin_length => ADCP_bin_length
+#	Nov 14, 2011: - added file layout check
 
 #--------------------------------------------------
 # Usage
@@ -18,6 +19,8 @@
 USAGE="Usage: $0 <eps-file> [in-file]"
 	[ $# -eq 2 ] && exec <"$2" "$0" "$1"
 	[ $# -ne 1 ] && { echo $USAGE >&2; exit 1; }
+
+eps_file="$1"
 
 #--------------------------------------------------
 # Read Header Data
@@ -36,6 +39,12 @@ do
 	[ -z "$ADCP_bin_length" ] && ADCP_bin_length=`expr -- "$line" : '#ANTS#PARAMS#.*ADCP_bin_length{\([^}]*\)}`
 	[ -z "$fields" ] && fields=`expr -- "$line" : '#ANTS#FIELDS# \(.*\)' | sed -e s/{//g -e s/}//g`
 done
+
+set -- $fields
+[ "$1" = ensemble -a "$4" = depth -a "${16}" = volume_scattering_coeff ] || {
+	echo "$0: file layout error" >&2
+	exit 1
+}
 
 #--------------------------------------------------
 # Plot Data
@@ -64,10 +73,10 @@ C=-C`which LWplot_Sv | sed 's@LWplot_Sv$@Sv.cpt@'`
 ens_width=`echo "scale=5;10/($max_ens-$min_ens+1)"|bc`
 bin_length=`echo "scale=5;10*$ADCP_bin_length/($max_depth-$min_depth+$ADCP_bin_length)"|bc`
 
-awk "{print \$1, \$4, \$14, $ens_width, $bin_length}" $TMPFILE \
-	| psxy -P -K $R $X $C -Sr > "$1"
+awk "{print \$1, \$4, \$16, $ens_width, $bin_length}" $TMPFILE \
+	| psxy -P -K $R $X $C -Sr > "$eps_file"
 	
-echo 0.02 0.02 12 0 0 TL $out_basename $run_label | pstext -O -K $U $X >> "$1"
+echo 0.02 0.02 12 0 0 TL $out_basename $run_label | pstext -O -K $U $X >> "$eps_file"
 
 if [ 0 -eq `echo "($max_depth-$min_depth)>1000"|bc` ]
 then
@@ -78,9 +87,9 @@ else
 	ens_tics=f500a1000
 fi
 
-cat `which LWplot_Sv | sed 's@LWplot_Sv$@Sv_scale.skel@'` >> "$1"
+cat `which LWplot_Sv | sed 's@LWplot_Sv$@Sv_scale.skel@'` >> "$eps_file"
 
-psbasemap -O $R $X -B$ens_tics:"Ensemble":/$depth_tics:"Depth [m]":WeSn >> "$1"
+psbasemap -O $R $X -B$ens_tics:"Ensemble":/$depth_tics:"Depth [m]":WeSn >> "$eps_file"
 
 rm $TMPFILE
-fixbb "$1"
+fixbb "$eps_file"
diff --git a/LWplot_TL b/LWplot_TL
--- a/LWplot_TL
+++ b/LWplot_TL
@@ -2,9 +2,9 @@
 #======================================================================
 #                    L W P L O T _ T L 
 #                    doc: Thu Oct 13 10:51:49 2011
-#                    dlm: Tue Oct 18 16:23:45 2011
+#                    dlm: Mon Nov 14 15:27:35 2011
 #                    (c) 2011 A.M. Thurnherr
-#                    uE-Info: 57 40 NIL 0 0 72 2 2 4 NIL ofnI
+#                    uE-Info: 31 88 NIL 0 0 72 2 2 4 NIL ofnI
 #======================================================================
 
 # HISTORY:
@@ -12,10 +12,12 @@
 #	Oct 14, 2011: - fiddled
 #	Oct 17, 2011: - turned into filter
 #				  - added %run_label
+#	Nov 14, 2011: - added file layout check
 
 USAGE="Usage: $0 <eps-file> [in-file]"
 	[ $# -eq 2 ] && exec <"$2" "$0" "$1"
 	[ $# -ne 1 ] && { echo $USAGE >&2; exit 1; }
+eps_file="$1"
 
 while [ -z "$fields" ]
 do
@@ -26,8 +28,14 @@ do
 	[ -z "$min_elapsed" ] && min_elapsed=`expr -- "$line" : '#ANTS#PARAMS#.*elapsed.min{\([^}]*\)}`
 	[ -z "$max_elapsed" ] && max_elapsed=`expr -- "$line" : '#ANTS#PARAMS#.*elapsed.max{\([^}]*\)}`
 	[ -z "$best_scan_offset" ] && best_scan_offset=`expr -- "$line" : '#ANTS#PARAMS#.*best_scan_offset{\([^}]*\)}`
-	[ -z "$fields" ] && fields=`expr -- "$line" : '#ANTS#FIELDS# \(.*\)' | sed -e s/{// -e s/}//`
+	[ -z "$fields" ] && fields=`expr -- "$line" : '#ANTS#FIELDS# \(.*\)' | sed -e s/{//g -e s/}//g`
 done
+
+set -- $fields
+[ "$1" = elapsed -a "$2" = scan_offset -a "$4" = downcast ] || {
+	echo "$0: file layout error ($1,$2,$4)" >&2
+	exit 1
+}
 
 TMPFILE=/tmp/$$.LWplot_TL
 if [ ! -t 1 ]
@@ -51,16 +59,16 @@ awk '{if ($4 == 1) { print $1/60,$2; }}' $TMPFILE \
 	| psxy -P -K $J $R \
 		   -Bf1a15:"Elapsed Time [min]":/f1a5:"Best Offset [scans]":WeSn \
 		   -Sc0.1 -Gcoral \
-	> "$1"		   
+	> "$eps_file"		   
 	
 awk '{if ($4 == 0) { print $1/60,$2; }}' $TMPFILE \
 	| psxy -O -K $J $R -Sc0.1 -GSeaGreen \
-	>> "$1"		   
+	>> "$eps_file"		   
 	
-echo 0.02 0.98 12 0 0 TL $out_basename $run_label | pstext -O -K $U $J >> "$1"
+echo 0.02 0.98 12 0 0 TL $out_basename $run_label | pstext -O -K $U $J >> "$eps_file"
 
 echo -e "`echo $min_elapsed/60|bc` $best_scan_offset\n`echo $max_elapsed/60+1|bc` $best_scan_offset" \
-	| psxy -O $R $J >> "$1"
+	| psxy -O $R $J >> "$eps_file"
 
 rm $TMPFILE
-fixbb "$1"
+fixbb "$eps_file"
diff --git a/LWplot_TLhist b/LWplot_TLhist
--- a/LWplot_TLhist
+++ b/LWplot_TLhist
@@ -2,19 +2,21 @@
 #======================================================================
 #                    L W P L O T _ T L H I S T 
 #                    doc: Thu Oct 13 10:51:49 2011
-#                    dlm: Mon Oct 17 15:15:23 2011
+#                    dlm: Mon Nov 14 15:27:46 2011
 #                    (c) 2011 A.M. Thurnherr
-#                    uE-Info: 53 0 NIL 0 0 72 2 2 4 NIL ofnI
+#                    uE-Info: 29 88 NIL 0 0 72 2 2 4 NIL ofnI
 #======================================================================
 
 # HISTORY:
 #	Oct 13, 2011: - created
 #	Oct 17, 2011: - turned into filter
 #				  - added %run_label
+#   Nov 14, 2011: - added file layout check
 
 USAGE="Usage: $0 <eps-file> [in-file]"
 	[ $# -eq 2 ] && exec <"$2" "$0" "$1"
 	[ $# -ne 1 ] && { echo $USAGE >&2; exit 1; }
+eps_file="$1"
 
 while [ -z "$fields" ]
 do
@@ -24,8 +26,14 @@ do
 	[ -z "$run_label" ] && run_label=`expr -- "$line" : '#ANTS#PARAMS#.*run_label{\([^}]*\)}`
 	[ -z "$n_windows" ] && n_windows=`expr -- "$line" : '#ANTS#PARAMS#.*n_windows{\([^}]*\)}`
 	[ -z "$best_scan_offset" ] && best_scan_offset=`expr -- "$line" : '#ANTS#PARAMS#.*best_scan_offset{\([^}]*\)}`
-	[ -z "$fields" ] && fields=`expr -- "$line" : '#ANTS#FIELDS# \(.*\)' | sed -e s/{// -e s/}//`
+	[ -z "$fields" ] && fields=`expr -- "$line" : '#ANTS#FIELDS# \(.*\)' | sed -e s/{//g -e s/}//g`
 done
+
+set -- $fields
+[ "$1" = scan_offset -a "$2" = nsamp ] || {
+	echo "$0: file layout error" >&2
+	exit 1
+}
 
 TMPFILE=/tmp/$$.LWplot_TLhist
 if [ ! -t 1 ]
@@ -48,12 +56,12 @@ J=-JX10
 awk "{print \$1, 100*\$2/$n_windows}" $TMPFILE \
 	| psxy -P -K $J $R \
 			-Bf1a10:"Best Offset [scans]":/f1a5:"Fraction [%]":WeSn \
-		    -Sb1u -G127 > "$1"
+		    -Sb1u -G127 > "$eps_file"
 	
-echo 0.02 0.98 12 0 0 TL $out_basename $run_label | pstext -O -K $J $U >> "$1"
+echo 0.02 0.98 12 0 0 TL $out_basename $run_label | pstext -O -K $J $U >> "$eps_file"
 
 echo -e "$best_scan_offset 0\n$best_scan_offset 60" \
-	| psxy -O $J $R >> "$1"
+	| psxy -O $J $R >> "$eps_file"
 
 rm $TMPFILE
-fixbb "$1"
+fixbb "$eps_file"
diff --git a/LWplot_prof b/LWplot_prof
--- a/LWplot_prof
+++ b/LWplot_prof
@@ -2,9 +2,9 @@
 #======================================================================
 #					 L W P L O T _ P R O F 
 #                    doc: Fri Oct 14 09:42:36 2011
-#                    dlm: Tue Oct 18 16:25:43 2011
+#                    dlm: Mon Nov 14 14:59:46 2011
 #                    (c) 2011 A.M. Thurnherr
-#                    uE-Info: 78 0 NIL 0 0 72 2 2 4 NIL ofnI
+#                    uE-Info: 44 65 NIL 0 0 72 2 2 4 NIL ofnI
 #======================================================================
 
 # HISTORY:
@@ -13,6 +13,7 @@
 #	Oct 16, 2011: - made depth tic-marks range dependent
 #	Oct 17, 2011: - turned into filter
 #				  - added %run_label
+#	Nov 14, 2011: - added file layout check
 
 #--------------------------------------------------
 # Usage
@@ -21,6 +22,7 @@
 USAGE="Usage: $0 <eps-file> [in-file]"
 	[ $# -eq 2 ] && exec <"$2" "$0" "$1"
 	[ $# -ne 1 ] && { echo $USAGE >&2; exit 1; }
+eps_file="$1"
 
 #--------------------------------------------------
 # Read Header Data
@@ -37,6 +39,18 @@ do
 	[ -z "$fields" ] && fields=`expr -- "$line" : '#ANTS#FIELDS# \(.*\)' | sed -e s/{//g -e s/}//g`
 done
 
+set -- $fields
+[ "$1" = depth -a "$4" = dc_w -a "$5" = dc_w.mad -a "$6" = dc_w.nsamp -a \
+  "$9" = uc_w  -a "${10}" = uc_w.mad -a "${11}" = uc_w.nsamp -a \
+  "${16}" = BT_w  -a "${17}" = BT_w.mad -a "${18}" = BT_w.nsamp ] || {
+		echo "$0: file layout error" >&2
+		exit 1
+}
+
+#--------------------------------------------------
+# Plot Data
+#--------------------------------------------------
+
 TMPFILE=/tmp/$$.LWplot_prof
 if [ ! -t 1 ]
 then
@@ -44,10 +58,6 @@ then
 else
 	cat > $TMPFILE
 fi
-
-#--------------------------------------------------
-# Plot Data
-#--------------------------------------------------
 
 [ -f .gmtdefaults4 ] ||
 	gmtset	PAPER_MEDIA letter+ \
@@ -60,26 +70,26 @@ R2=-R-200/200/$min_depth/$max_depth
 U=-R0/1/0/1
 X=-JX10/-10
 
-echo -e "0 $min_depth\n0 $max_depth" | psxy -P -K $R $X > "$1"
-echo -e "0.07 $min_depth\n0.07 $max_depth\n0.18 $max_depth\n0.18 $min_depth" | psxy -O -K $R $X -L -G200 >> "$1"
-echo -e "50 $min_depth\n50 $max_depth" | psxy -O -K $R2 $X >> "$1"
-echo -e "100 $min_depth\n100 $max_depth" | psxy -O -K $R2 $X >> "$1"
-echo -e "150 $min_depth\n150 $max_depth" | psxy -O -K $R2 $X >> "$1"
+echo -e "0 $min_depth\n0 $max_depth" | psxy -P -K $R $X > "$eps_file"
+echo -e "0.07 $min_depth\n0.07 $max_depth\n0.18 $max_depth\n0.18 $min_depth" | psxy -O -K $R $X -L -G200 >> "$eps_file"
+echo -e "50 $min_depth\n50 $max_depth" | psxy -O -K $R2 $X >> "$eps_file"
+echo -e "100 $min_depth\n100 $max_depth" | psxy -O -K $R2 $X >> "$eps_file"
+echo -e "150 $min_depth\n150 $max_depth" | psxy -O -K $R2 $X >> "$eps_file"
 
-awk '{print $4, $1}' $TMPFILE | psxy -O -K -N -Mn $R $X -W4/coral >> "$1"
-awk '{print $9, $1}' $TMPFILE | psxy -O -K -N -Mn $R $X -W4/SeaGreen >> "$1"
-awk '{print $16,$1}' $TMPFILE | psxy -O -K -N -Mn $R $X -W4/black >> "$1"
+awk '{print $4, $1}' $TMPFILE | psxy -O -K -N -Mn $R $X -W4/coral >> "$eps_file"
+awk '{print $9, $1}' $TMPFILE | psxy -O -K -N -Mn $R $X -W4/SeaGreen >> "$eps_file"
+awk '{print $16,$1}' $TMPFILE | psxy -O -K -N -Mn $R $X -W4/black >> "$eps_file"
 	
-awk '{print  $5,$1, $4}' $TMPFILE | grep -vi nan | psxy -O -K -N  $R $X -Sc0.1c -Gcoral >> "$1"
-awk '{print $10,$1, $9}' $TMPFILE | grep -vi nan | psxy -O -K -N  $R $X -Sc0.1c -GSeaGreen >> "$1"
-awk '{print $17,$1,$16}' $TMPFILE | grep -vi nan | psxy -O -K -N  $R $X -Sc0.1c -Gblack >> "$1"
+awk '{print  $5,$1, $4}' $TMPFILE | grep -vi nan | psxy -O -K -N  $R $X -Sc0.1c -Gcoral >> "$eps_file"
+awk '{print $10,$1, $9}' $TMPFILE | grep -vi nan | psxy -O -K -N  $R $X -Sc0.1c -GSeaGreen >> "$eps_file"
+awk '{print $17,$1,$16}' $TMPFILE | grep -vi nan | psxy -O -K -N  $R $X -Sc0.1c -Gblack >> "$eps_file"
 
-awk '{print  $6,$1,$4}' $TMPFILE | sed '/nan/s/.*/nan/' | psxy -O -K -N -Mn $R2 $X -W1/coral >> "$1"
-awk '{print $11,$1,$9}' $TMPFILE | sed '/nan/s/.*/nan/' | psxy -O -K -N -Mn $R2 $X -W1/SeaGreen >> "$1"
-awk '{print $18,$1,$16}' $TMPFILE | sed '/nan/s/.*/nan/' | psxy -O -K -N -Mn $R2 $X -W1/black >> "$1"
+awk '{print  $6,$1,$4}' $TMPFILE | sed '/nan/s/.*/nan/' | psxy -O -K -N -Mn $R2 $X -W1/coral >> "$eps_file"
+awk '{print $11,$1,$9}' $TMPFILE | sed '/nan/s/.*/nan/' | psxy -O -K -N -Mn $R2 $X -W1/SeaGreen >> "$eps_file"
+awk '{print $18,$1,$16}' $TMPFILE | sed '/nan/s/.*/nan/' | psxy -O -K -N -Mn $R2 $X -W1/black >> "$eps_file"
 
-echo 0.02 0.02 12 0 0 TL $out_basename $run_label | pstext -O -K $U $X >> "$1"
-echo 0.6 0.98 12 0 0 BR m.a.d. | pstext -O -K $U $X >> "$1"
+echo 0.02 0.02 12 0 0 TL $out_basename $run_label | pstext -O -K $U $X >> "$eps_file"
+echo 0.6 0.98 12 0 0 BR m.a.d. | pstext -O -K $U $X >> "$eps_file"
 
 if [ 0 -eq `echo "($max_depth-$min_depth)>1000"|bc` ]
 then
@@ -88,13 +98,13 @@ else
 	depth_tics=f100a500
 fi
 
-psbasemap -O -K $R $X -Bf0.01a10-10.05:"Vertical Velocity [m/s]                               ":/$depth_tics:"Depth [m]":WeS >> "$1"
-psbasemap -O -K $R $X -Ba10-9.95S >> "$1"
-psbasemap -O -K $R $X -Ba10-9.85S >> "$1"
+psbasemap -O -K $R $X -Bf0.01a10-10.05:"Vertical Velocity [m/s]                               ":/$depth_tics:"Depth [m]":WeS >> "$eps_file"
+psbasemap -O -K $R $X -Ba10-9.95S >> "$eps_file"
+psbasemap -O -K $R $X -Ba10-9.85S >> "$eps_file"
 
-psbasemap -O -K $R2 $X -Bf10a1000-950:"                                     # of Samples":N >> "$1"
-psbasemap -O -K $R2 $X -Ba1000-900N >> "$1"
-psbasemap -O $R2 $X -Ba1000-850N >> "$1"
+psbasemap -O -K $R2 $X -Bf10a1000-950:"                                     # of Samples":N >> "$eps_file"
+psbasemap -O -K $R2 $X -Ba1000-900N >> "$eps_file"
+psbasemap -O $R2 $X -Ba1000-850N >> "$eps_file"
 		 
 rm $TMPFILE
-fixbb "$1"
+fixbb "$eps_file"
diff --git a/LWplot_residuals b/LWplot_residuals
--- a/LWplot_residuals
+++ b/LWplot_residuals
@@ -2,9 +2,9 @@
 #======================================================================
 #					 L W P L O T _ R E S I D U A L S 
 #                    doc: Sat Oct 15 13:42:50 2011
-#                    dlm: Mon Oct 24 10:29:32 2011
+#                    dlm: Mon Nov 14 14:53:06 2011
 #                    (c) 2011 A.M. Thurnherr
-#                    uE-Info: 15 0 NIL 0 0 72 2 2 4 NIL ofnI
+#                    uE-Info: 77 26 NIL 0 0 72 2 2 4 NIL ofnI
 #======================================================================
 
 # HISTORY:
@@ -12,6 +12,7 @@
 #	Oct 17, 2011: - turned into filter
 #				  - added %run_label
 #   Oct 24, 2011: - LADCP_bin_length => ADCP_bin_length
+#	Nov 14, 2011: - added file layout check
 
 #--------------------------------------------------
 # Usage
@@ -20,6 +21,7 @@
 USAGE="Usage: $0 <eps-file> [in-file]"
 	[ $# -eq 2 ] && exec <"$2" "$0" "$1"
 	[ $# -ne 1 ] && { echo $USAGE >&2; exit 1; }
+eps_file="$1"
 
 #--------------------------------------------------
 # Read Header Data
@@ -38,6 +40,12 @@ do
 	[ -z "$ADCP_bin_length" ] && ADCP_bin_length=`expr -- "$line" : '#ANTS#PARAMS#.*ADCP_bin_length{\([^}]*\)}`
 	[ -z "$fields" ] && fields=`expr -- "$line" : '#ANTS#FIELDS# \(.*\)' | sed -e s/{//g -e s/}//g`
 done
+
+set -- $fields
+[ "$1" = ensemble -a "$4" = depth -a "${10}" = residual ] || {
+	echo "$0: file layout error ($1, $4, ${10})" >&2
+	exit 1
+}
 
 #--------------------------------------------------
 # Plot Data
@@ -66,10 +74,10 @@ C=-C`which LWplot_residuals | sed 's@LWplot_residuals$@residuals.cpt@'`
 ens_width=`echo "scale=5;10/($max_ens-$min_ens+1)"|bc`
 bin_length=`echo "scale=5;10*$ADCP_bin_length/($max_depth-$min_depth+$ADCP_bin_length)"|bc`
 
-awk "{print \$1, \$4, \$8, $ens_width, $bin_length}" $TMPFILE \
-	| psxy -P -K $R $X $C -Sr > "$1"
+awk "{print \$1, \$4, \$10, $ens_width, $bin_length}" $TMPFILE \
+	| psxy -P -K $R $X $C -Sr > "$eps_file"
 	
-echo 0.02 0.02 12 0 0 TL $out_basename $run_label | pstext -O -K $U $X >> "$1"
+echo 0.02 0.02 12 0 0 TL $out_basename $run_label | pstext -O -K $U $X >> "$eps_file"
 
 if [ 0 -eq `echo "($max_depth-$min_depth)>1000"|bc` ]
 then
@@ -80,9 +88,9 @@ else
 	ens_tics=f500a1000
 fi
 
-cat `which LWplot_residuals | sed 's@LWplot_residuals$@residuals_scale.skel@'` >> "$1"
+cat `which LWplot_residuals | sed 's@LWplot_residuals$@residuals_scale.skel@'` >> "$eps_file"
 
-psbasemap -O $R $X -B$ens_tics:"Ensemble":/$depth_tics:"Depth [m]":WeSn >> "$1"
+psbasemap -O $R $X -B$ens_tics:"Ensemble":/$depth_tics:"Depth [m]":WeSn >> "$eps_file"
 
 rm $TMPFILE
-fixbb "$1"
+fixbb "$eps_file"
