a few days pre WHOI

diff --git a/LWplot_prof b/LWplot_prof
--- a/LWplot_prof
+++ b/LWplot_prof
@@ -2,9 +2,9 @@
 #======================================================================
 #					 L W P L O T _ P R O F 
 #                    doc: Fri Oct 14 09:42:36 2011
-#                    dlm: Thu Apr 16 10:41:09 2015
+#                    dlm: Wed May 20 20:45:55 2015
 #                    (c) 2011 A.M. Thurnherr
-#                    uE-Info: 24 0 NIL 0 0 72 2 2 4 NIL ofnI
+#                    uE-Info: 56 0 NIL 0 0 72 2 2 4 NIL ofnI
 #======================================================================
 
 # HISTORY:
@@ -21,6 +21,12 @@
 #	Apr  5, 2015: - made fixbb optional
 #   Apr 16, 2015: - removed copy of input on stdout
 #				  - changed shell from /bin/ksh to /bin/sh
+#	Apr 26, 2015: - adapted to LADCP_w_regrid output
+#				  - removed -N
+#				  - moved run_label above plot area
+#	May 19, 2015: - adapted to new layout (hab)
+#				  - BUG: erroneously let .VKE profiles pass
+#   May 20, 2015: - made it quit on EOF
 
 #--------------------------------------------------
 # Usage
@@ -35,21 +41,24 @@ eps_file="$1"
 # Read Header Data
 #--------------------------------------------------
 
-while [ -z "$fields" ]
+read line
+while [ -z "$done" -a -n "$line" ]
 do
-	read line
 	[ -z "$out_basename" ] && out_basename=`expr -- "$line" : '#ANTS#PARAMS#.*out_basename{\([^}]*\)}`
 	[ -z "$run_label" ] && run_label=`expr -- "$line" : '#ANTS#PARAMS#.*run_label{\([^}]*\)}`
 	[ -z "$min_depth" ] && min_depth=`expr -- "$line" : '#ANTS#PARAMS#.*min_depth{\([^}]*\)}`
 	[ -z "$max_depth" ] && max_depth=`expr -- "$line" : '#ANTS#PARAMS#.*max_depth{\([^}]*\)}`
-	[ -z "$fields" ] && fields=`expr -- "$line" : '#ANTS#FIELDS# \(.*\)' | sed -e s/{//g -e s/}//g`
+	[ -z "$water_depth" ] && water_depth=`expr -- "$line" : '#ANTS#PARAMS#.*water_depth{\([^}]*\)}`
+	newfields=`expr -- "$line" : '#ANTS#FIELDS# \(.*\)' | sed -e s/{//g -e s/}//g`
+	[ -z "$newfields" ] || fields=$newfields
+	done=`expr -- "$line" : '^[^#]\(.*\)'`
+	read line
 done
 
 set -- $fields
 [ "$1" = depth -a "$4" = dc_w -a "$5" = dc_w.mad -a "$6" = dc_w.nsamp -a \
-  "${11}" = uc_w  -a "${12}" = uc_w.mad -a "${13}" = uc_w.nsamp -a \
-  "${20}" = BT_w  -a "${21}" = BT_w.mad -a "${22}" = BT_w.nsamp ] || {
-		echo "$0: file layout error" >&2
+  "$8" = uc_w  -a "$9" = uc_w.mad -a "${10}" = uc_w.nsamp ] || {
+		echo "$0: file layout error ($1, $4, $5, $6, $8, $9, ${10})" >&2
 		exit 1
 }
 
@@ -62,7 +71,10 @@ mkdir /tmp/$$				# GMT makes tmpfiles and is not reentrant
 cd /tmp/$$
 
 TMPFILE=/tmp/$$.LWplot_prof
-cat > $TMPFILE
+{
+	echo $line
+	sed s/#.*//
+} > $TMPFILE
 
 [ -f .gmtdefaults4 ] ||
 	gmtset	PAPER_MEDIA letter+ \
@@ -70,8 +82,16 @@ cat > $TMPFILE
 			WANT_EURO_FONT true \
 	        PLOT_DEGREE_FORMAT ddd:mm:ssF
 
-R=-R-0.07/0.35/$min_depth/$max_depth
-R2=-R-200/200/$min_depth/$max_depth
+[ -n "$water_depth" ] && blim=`echo "scale=0;$water_depth/1+25"|bc` \
+				      || blim=`echo "scale=0;$max_depth/1+25"|bc`
+
+XTICS="-0.05 0.05 0.15"
+XMIN=-0.1
+
+[ -r ./.LWplot_prof ] && . ./.LWplot_prof
+
+R=-R$XMIN/0.35/0/$blim
+R2=-R-200/200/0/$blim
 U=-R0/1/0/1
 X=-JX10/-10
 
@@ -83,22 +103,27 @@ X=-JX10/-10
 { echo 150 $min_depth; echo 150 $max_depth; } | psxy -O -K $R2 $X >> "$eps_file"
 
 # VERTICAL VELOCITIES
-awk '{print $4, $1}' $TMPFILE | psxy -O -K -N -Mn $R $X -W4/coral >> "$eps_file"
-awk '{print $11,$1}' $TMPFILE | psxy -O -K -N -Mn $R $X -W4/SeaGreen >> "$eps_file"
-awk '{print $20,$1}' $TMPFILE | psxy -O -K -N -Mn $R $X -W4/black >> "$eps_file"
+awk '{print $4,$1}' $TMPFILE | psxy -O -K  -Mn $R $X -W4/coral >> "$eps_file"
+awk '{print $8,$1}' $TMPFILE | psxy -O -K  -Mn $R $X -W4/SeaGreen >> "$eps_file"
 	
-# MEAN ABSOLUTE DEVIATIONS (COMBINED SOLUTION)
-awk '{print  $5,$1, $4}' $TMPFILE | grep -vi nan | psxy -O -K -N  $R $X -Sc0.1c -Gcoral >> "$eps_file"
-awk '{print $12,$1,$11}' $TMPFILE | grep -vi nan | psxy -O -K -N  $R $X -Sc0.1c -GSeaGreen >> "$eps_file"
-awk '{print $21,$1,$20}' $TMPFILE | grep -vi nan | psxy -O -K -N  $R $X -Sc0.1c -Gblack >> "$eps_file"
+# MEAN ABSOLUTE DEVIATIONS
+awk '{print $5,$1,$4}' $TMPFILE | grep -vi nan | psxy -O -K   $R $X -Sc0.1c -Gcoral >> "$eps_file"
+awk '{print $9,$1,$8}' $TMPFILE | grep -vi nan | psxy -O -K   $R $X -Sc0.1c -GSeaGreen >> "$eps_file"
 
-# NUMBER OF SAMPLES (COMBINED SOLUTION)
-awk '{print  $6,$1, $4}' $TMPFILE | sed '/nan/s/.*/nan/' | psxy -O -K -N -Mn $R2 $X -W1/coral >> "$eps_file"
-awk '{print $13,$1,$11}' $TMPFILE | sed '/nan/s/.*/nan/' | psxy -O -K -N -Mn $R2 $X -W1/SeaGreen >> "$eps_file"
-awk '{print $22,$1,$20}' $TMPFILE | sed '/nan/s/.*/nan/' | psxy -O -K -N -Mn $R2 $X -W1/black >> "$eps_file"
+# NUMBER OF SAMPLES
+awk '{print $6,$1,$5}' $TMPFILE | sed '/nan/s/.*/nan/' | psxy -O -K  -Mn $R2 $X -W1/coral >> "$eps_file"
+awk '{print $10,$1,$9}' $TMPFILE | sed '/nan/s/.*/nan/' | psxy -O -K  -Mn $R2 $X -W1/SeaGreen >> "$eps_file"
+
+# SEABED
+[ -n "$water_depth" ] && {
+	echo $XMIN $blim;
+	echo 0.35 $blim;
+	echo 0.35 $water_depth;
+	echo $XMIN $water_depth;
+} | psxy -O -K $R $X -G204/153/102 >> "$eps_file"
 
 # LABELS
-echo 0.02 0.02 12 0 0 TL $out_basename $run_label | pstext -O -K $U $X >> "$eps_file"
+echo 0.02 -0.05 10 0 0 TL $out_basename $run_label | pstext -O -K -Gblue -N $U $X >> "$eps_file"
 echo 0.6 0.98 12 0 0 BR m.a.d. | pstext -O -K $U $X >> "$eps_file"
 
 if [ 0 -eq `echo "($max_depth-$min_depth)>1000"|bc` ]
